seed = 12345
step_duration = 20
drag = 0.0
stddev_x = 0.2
stddev_y = 0.2
allow_noop = false

[ball]
    starts = [[0.2, 0.9], [0.9, 0.9], [0.9, 0.2], [0.1, 0.1]] # List of possible starting points.
    radius = 0.02

[target]
    location = [0.9, 0.2]
    radius = 0.04
    
# Board boundary
[[obstacles]]
    points = [[0.0, 0.0], [0.0, 0.01], [1.0, 0.01], [1.0, 0.0]]
[[obstacles]]
    points = [[0.0, 0.0], [0.01, 0.0], [0.01, 1.0], [0.0, 1.0]]
[[obstacles]]
    points = [[0.0, 1.0], [0.0, 0.99], [1.0, 0.99], [1.0, 1.0]]
[[obstacles]]
    points = [[1.0, 1.0], [0.99, 1.0], [0.99, 0.0], [1.0, 0.0]]

# Obstacles
[[obstacles]]
    points = [[0.35, 0.4], [0.45, 0.55], [0.43, 0.65], [0.3, 0.7], [0.45, 0.7], [0.5, 0.6], [0.45, 0.35]]
[[obstacles]]
    points = [[0.2, 0.6], [0.25, 0.55], [0.15, 0.5], [0.15, 0.45], [0.2, 0.3], [0.12, 0.27], [0.075, 0.35], [0.09, 0.55]]
[[obstacles]]
    points = [[0.3, 0.8], [0.6, 0.75], [0.8, 0.8], [0.8, 0.9], [0.6, 0.85], [0.3, 0.9]]
[[obstacles]]
    points = [[0.8, 0.7], [0.975, 0.65], [0.75, 0.5], [0.9, 0.3], [0.7, 0.35], [0.63, 0.65]]
[[obstacles]]
    points = [[0.6, 0.25], [0.3, 0.07], [0.15, 0.175], [0.15, 0.2], [0.3, 0.175], [0.6, 0.3]]
[[obstacles]]
    points = [[0.75, 0.025], [0.8, 0.24], [0.725, 0.27], [0.7, 0.025]]